segment_web_tech = {
'Active Campaign': 'ActiveCampaign',
'AdRoll': 'AdRoll',
'Adjust': 'Adjust',
'Amazon S3': 'Amazon S3',
'Amplitude': 'Amplitude',
'AppNexus': 'AppNexus',
'AppBoy': 'Appboy',
'Autopilot': 'AutopilotHQ',
'Bing Ads': 'Bing Ads',
'Blueshift': 'Blueshift',
'Branch Metrics': 'Branch Metrics',
'Bronto': 'Bronto',
'BugHerd': 'BugHerd',
'Chartbeat': 'Chartbeat',
'Clicky': 'Clicky',
'comScore': 'comScore',
'Convertro (AOL)': 'Convertro',
'CrazyEgg': 'Crazy Egg',
'Crittercism': 'Crittercism',
'Curebit (Talkable)': 'Curebit',
'Customer.IO': 'Customer.io',
'DataXu': 'DataXu',
'Drip': 'Drip',
'Elevio': 'Elevio',
'Eloqua': 'Eloqua',
'Errorception': 'Errorception',
'Evergage': 'Evergage',
'ExactTarget': 'Salesforce Marketing Cloud',
'Extole': 'Extole',
'Facebook Conversion Tracking': 'Facebook Pixel',
'Facebook SDK': 'Facebook App Events',
'Facebook Web Custom Audiences': 'Facebook Pixel',
'Facebook WCA Page View': 'Facebook Pixel',
'Flurry': 'Flurry',
'Freshdesk': 'Freshdesk',
'FullStory': 'FullStory',
'Gauges': 'Gauges',
'GoSquared': 'GoSquared',
'Google Adwords Conversion': 'AdWords',
'Google Analytics': 'Google Analytics',
'Google Dynamic Remarketing': 'AdWords',
'Google Tag Manager': 'Google Tag Manager',
'Google Universal Analytics': 'Google Analytics',
'HasOffers': 'HasOffers',
'HeapAnalytics': 'Heap',
'Hellobar': 'Hello Bar',
'HelpScout': 'Help Scout',
'HitTail': 'HitTail',
'Hubspot': 'HubSpot',
'Improvely': 'Improvely',
'Inspectlet': 'Inspectlet',
'Intercom': 'Intercom',
'Kissmetrics': 'KISSmetrics',
'Kahuna': 'Kahuna',
'Keen IO': 'Keen IO',
'Klaviyo': 'Klaviyo',
'Kochava': 'Kochava',
'Leanplum': 'Leanplum',
'LiveChat': 'LiveChat',
'Localytics': 'Localytics',
'Lucky Orange': 'Lucky Orange',
'MailChimp': 'MailChimp',
'MailChimp SPF': 'MailChimp',
'Mailchimp Mandrill': 'Mandrill',
'MailJet': 'Mailjet',
'Marketo': 'Marketo',
'MediaMath': 'MediaMath',
'Millennial Media': 'Millennial Media',
'Mixpanel': 'Mixpanel',
'MoEngage': 'MoEngage',
'MobileAppTracking by TUNE': 'MobileAppTracking',
'Mojn': 'Mojn',
'Monetate': 'Monetate',
'MouseFlow': 'Mouseflow',
'Nanigans': 'Nanigans',
'New Relic': 'New Relic',
'Nudgespot': 'Nudgespot',
'Olark': 'Olark',
'Omniture (Adobe)': 'Omniture',
'OneSignal': 'OneSignal',
'Optimizely': 'Optimizely',
'Pardot': 'Pardot',
'Perfect Audience (Marin Software)': 'Perfect Audience',
'Segment.io': 'Segment',
'Pingdom': 'Pingdom',
'Piwik': 'Piwik',
'Qualaroo': 'Qualaroo',
'Quantcast': 'Quantcast',
'Rollbar': 'Rollbar',
'Salesforce': 'Salesforce',
'Sendgrid': 'SendGrid',
'Sentry': 'Sentry',
'ShareASale': 'ShareASale',
'SimpleReach': 'SimpleReach',
'SnapEngage': 'SnapEngage',
'Spinnakr': 'Spinnakr',
'Stripe': 'Stripe',
'Taplytics': 'Taplytics',
'Tapstream': 'Tapstream',
'Totango': 'Totango',
'Twilio': 'Twilio',
'UserVoice': 'UserVoice',
'UserLike': 'Userlike',
'Vero': 'Vero',
'WebEngage': 'WebEngage',
'Webtrends': 'Webtrends',
'Woopra': 'Woopra',
'Zendesk': 'Zendesk',
'Zopim by Zendesk': 'Zopim',
'Twitter Advertising': 'Twitter Ads',
'Wordpress.org': 'Wordpress',
'Wordpress.com': 'Wordpress',
'Yandex Metrica': 'Yandex Metrica',
'Visual Website Optimizer': 'Visual Website Optimizer'
}
